### ISSUE TITLE
Empty Rakefile breaks everything

### ISSUE THREAD

**Issue by panjan** [pezra/rspec-mode#135]
Hello, I tried to run tests on a project with an empty Rakefile and got the following output:

```
-*- mode: rspec-compilation; default-directory: "~/project/" -*-
RSpec Compilation started at Thu Jan  7 11:57:25

bundle exec rake spec SPEC_OPTS='--options ~/project/.rspec' SPEC='~/project/spec'

RSpec Compilation finished at Thu Jan  7 11:57:26
```
This is the minimal working Rakefile:
```
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)
```
Things should work even with an empty Rakefile.

**Comment by dgutov** [comment]
How will we check whether Rakefile is a "working" one?

**Comment by panjan** [comment]
How about looking for the `spec` task in the output of `rake --tasks --all`?

**Comment by dgutov** [comment]
That would be pretty slow: first, we have to use `bundle exec` anyway. If `Rakefile` loads the environment, we'll basically incur the gem loading overhead twice.

In one of my work projects, that takes ~4 seconds. An sample Rails project: 2 seconds.

**Comment by dgutov** [comment]
Maybe the better choice would be to simply make `rspec-use-rake-when-possible` default to nil. I definitely had to use this value in the recent projects at works.

@pezra What do you think?

**Comment by pezra** [comment]
Hmm... it has the downside of breaking projects that do setup work in rake. (Eg, every rails project whenever there is a new migration.) Otoh, it would make individual test runs a bit, or a lot, faster.

I think I lean toward changing the default as @dgutov suggests because I rarely use rake to run specs these days. Even in rails projects. I'd be interested in hearing the views of others in the community, thoguh. (@rranelli, @pedz, @timcharper, @asok, @dgtized ,etc)

**Comment by rranelli** [comment]
I too never run "rake test" with rspec mode. I have set the option to
ignore the Rakefile since my first day with rspec-mode I guess.

**Comment by pedz** [comment]
I also have it set to nil.  I wrote what I call [prvm](https://github.com/pedz/my.emacs.d/blob/master/pedz/prvm.el) which puts rspec with the bundled environment in my path so I can just say "rspec" and it is set up properly.
