### ISSUE TITLE
Setting docker variables, does nothing

### ISSUE THREAD

**Issue by Fibrasek** [pezra/rspec-mode#178]
Hello,

I have setup the variables to run via docker, but it seems to do nothing, here is my config:
```elisp
(use-package rspec-mode
  :ensure t
  :init (setq rspec-use-rvm t
              rspec-use-docker-when-possible t
              rspec-docker-command "docker exec"
              rspec-docker-cwd "/b2beauty/beautydate/"
              rspec-docker-container "beautydate_web_1"))
```

And the output from `C-c , v`:
```
-*- mode: rspec-compilation; default-directory: "~/Dev/BeautyDate/beautydate/" -*-
RSpec Compilation started at Mon Sep 10 12:28:45

bundle exec rspec --format documentation /home/fibrasek/Dev/BeautyDate/beautydate/spec/models/sales_order_spec.rb
```

Am I doing something wrong? If so, what?

**Comment by dgutov** [comment]
Is there a Dockerfile in the project root?

**Comment by Fibrasek** [comment]
@dgutov yes, but they end with different extensions, eg.: `Dockerfile.aws`

**Comment by dgutov** [comment]
How do you choose which one to use?

**Comment by Fibrasek** [comment]
Locally its used via `docker-compose`

**Comment by dgutov** [comment]
What is?

**Comment by Fibrasek** [comment]
You can read about `docker-compose` [here](https://docs.docker.com/compose/overview/)

**Comment by micdahl** [comment]
It is because there is a function which searches for "Dockerfile" to determine the docker root directory. If there is none, the use of docker is disabled. This was intended to enable `docker-compose` from the root directory of the project, if some files deeper in the directory tree are beeing edited when rspec mode is run. As a quick workaround you can create an empty Dockerfile in your apps root directory.

To resolve the issue, there could be a distinction if `docker` or `docker-compose` are given as `rspec-docker-command`. Also it would be reasonable to look for "docker-compose.yml" instead of "Dockerfile" and/or to allow a variable filename to find projects root.

**Comment by Fibrasek** [comment]
@micdahl seems a reasonable workaround. Extending the topic, which function looks for the `Dockerfile` in the project root? Maybe extending how it searches for the file could solve the issue of having multiple `Dockerfiles` with extensions.

**Comment by dgutov** [comment]
@Fibrasek You can certainly use advice on `rspec-docker-p` to make it behave however you like.

@micdahl Not sure simply removing the existence check is the correct approach. After all, all other similar variables work that way. At the very least, the option would have to be renamed.

**Comment by Fibrasek** [comment]
@dgutov thanks for the tip, Ill look up on how to properly use advice, since my lisp skills are pretty basic :smile:

**Comment by nfedyashev** [comment]
I believe that it is worth mentioning in README that rspec-mode expects to find Dockerfile in the root directory. For new users it is very confusing because having Dockerfile in non-root directory is pretty common practice(for example https://github.com/evilmartians/terraforming-rails/tree/master/examples/dockerdev ).

Other than that `rspec-mode` is awesome

**Comment by dgutov** [comment]
@nfedyashev How can we support this use case? Can we just look for `docker-compose.yml` as well?

**Comment by nfedyashev** [comment]
@dgutov 

>Can we just look for docker-compose.yml as well?

yes or checking for the presence of files named like docker-compose* - it covers cases like 

>docker-compose.yml
>docker-compose.consul.yml
>docker-compose.dev.yml
>docker-compose.prod.yml
>docker-compose.override.yml
>docker-compose.sec.yml
>docker-compose.storage.yml
>docker-compose.sync.yml
>docker-compose.development.yml

Examples were taken from https://github.com/search?q=docker-compose&type=Code

**Comment by dgutov** [comment]
I think most of those are used for scripting purposes, don't they? Like, the CI script copies `docker-compose.gitlab.yml` to `docker-compose.yml` before running the build.

In any case, I can simply add a custom var with the file name to look for.

**Comment by nfedyashev** [comment]
Although I never used custom docker-compose yaml confg files(like docker-compose.custom.yml) I suspect some may use it for expressiveness/explicitness in their complex projects.

CI script most likely doesn't need to copy/rename docker-compose config files because it can explicitly specify which config to pick up using `docker-compose -f docker-compose.custom.yml` 

>In any case, I can simply add a custom var with the file name to look for.

:+1: 
and the default value would be "docker-compose.yml"? This should solve the issue for most generic projects and make it really easy to understand what to do in the case of custom Compose files because it is explicit and clear in form of variable name.

**Comment by dgutov** [comment]
> and the default value would be "docker-compose.yml"?

Why not "Dockerfile"? :)

In your experience, do people use Docker without docker-compose these days?

**Comment by pedz** [comment]
I have never used docker compose but I believe I’m the minority.

How about a list?

**Comment by dgutov** [comment]
I'm, uh, trying to minimize the number of disk accesses in the default config (mostly important when one uses Tramp). The var could be a list, but the default would have one element.

Speaking of, one of the recent PRs sneaked in a change in the default of `rspec-docker-command`. @pedz, did you have to customize that?

**Comment by pedz** [comment]
I’ve not used Docker with Ruby On Rails.  I was using it with Python.

Given that this is Docker + RoR + Development (since this is using Rspec) … I’d go with docker compose.

I’m very curious to explore this.  I spent two weeks exploring using Virtual Box, Vagrant, and Arch Linux
just so I didn’t have to install (evil) Chrome on my laptop.  Turns out you can use Brave instead of Chrome.

**Comment by dgutov** [comment]
> Given that this is Docker + RoR + Development (since this is using Rspec) … I’d go with docker compose

Excellent, docker-compose it is!

> Turns out you can use Brave instead of Chrome

Or, um, Firefox?

**Comment by nfedyashev** [comment]
@dgutov 
>>and the default value would be "docker-compose.yml"?
>Why not "Dockerfile"? :)
oh, sorry, I might have misunderstood your point.
I thought that's going to be combined check(presence of Dockerfile OR docker-compose.yml).

>In your experience, do people use Docker without docker-compose these days?
I guess some people might be still using Docker without docker-compose.

**Comment by dgutov** [comment]
> some people might be still using Docker without docker-compose

Then they have to customize `docker-command` anyway.
